apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nk1yv0uw3-nodejs 
  janus-idp.io/tekton: nk1yv0uw3-nodejs
  backstage.io/kubernetes-id: nk1yv0uw3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nk1yv0uw3-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml